name: Check

on: push

jobs:
  cancel-workflow-action:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
      - uses: actions/checkout@v1
      - uses: randy3k/actions/run-rchk@rchk

  ubsan:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-devel-ubsan-clang
      options: --cap-add=SYS_PTRACE
    env:
      _R_CHECK_CRAN_INCOMING_: false
    steps:
      - uses: actions/checkout@v1
      - name: Setup
        run: |
          ln -sf /usr/local/bin/RD /usr/local/bin/R
          ln -sf /usr/local/bin/RDscript /usr/local/bin/Rscript
          echo R_LIBS_USER=/usr/local/lib/R/site-library >> $GITHUB_ENV
        shell: bash
      - uses: randy3k/gh-actions/r-install-deps@main
        with:
          extra-packages: rcmdcheck
      - name: Running Tests
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual'), error_on = 'warning')"
