name: Check

on:
  push:

jobs:
  cleanup:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
      - uses: actions/checkout@v1
      - uses: randy3k/actions/run-rchk@rchk

  ubsan:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-devel-ubsan-clang
      options: --cap-add=SYS_PTRACE
    env:
      _R_CHECK_CRAN_INCOMING_: false
    steps:
      - uses: actions/checkout@v1
      - run: |
          ln -s /usr/local/bin/RD /usr/local/bin/R
          ln -s /usr/local/bin/RDscript /usr/local/bin/Rscript
          echo R_LIBS_USER=/usr/local/lib/R/library >> $GITHUB_ENV
        shell: bash
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck
          cache-version: ubsan-1
      - name: Running Tests
        run: |
          RDscript -e "rcmdcheck::rcmdcheck(args = c('--as-cran', '--no-manual'), error_on = 'warning')"

  csan:
    runs-on: ubuntu-latest
    container:
      image: wch1/r-debug
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v1
      - run: |
          ln -s /usr/local/bin/RDcsan /usr/local/bin/R
          ln -s /usr/local/bin/RDscriptcsan /usr/local/bin/Rscript
          echo R_LIBS_USER=/usr/local/RDcsan/lib/R/site-library >> $GITHUB_ENV
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck
          cache-version: csan-2


      - uses: r-lib/actions/check-r-package@v1

      - name: remove _cache directory
        run: |
          rm -rf /usr/local/RDcsan/lib/R/site-library/_cache/

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
