name: Check

on:
  push:

jobs:
  cleanup:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  rchk:
    runs-on: ubuntu-latest
    container:
      image: rhub/ubuntu-rchk
      options: --user=root
    steps:
      - uses: actions/checkout@v1
      - uses: randy3k/actions/run-rchk@rchk

  csan:
    runs-on: ubuntu-latest
    container:
      image: wch1/r-debug
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v1
      - run: |
          ln -s /usr/local/bin/RDcsan /usr/local/bin/R
          ln -s /usr/local/bin/RDscriptcsan /usr/local/bin/Rscript
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck
          cache-version: csan-1
        env:
           R_LIBS_USER: /usr/local/RDcsan/lib/R/site-library

      - uses: r-lib/actions/check-r-package@v1

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
